name: grass
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # normal
  intl: ^0.16.0
  json_annotation: ^3.0.1
  provider: ^4.0.4
  path: ^1.6.4
  path_provider: ^1.6.5
  shared_preferences: ^0.5.6+3
  sqflite: ^1.3.0
  mobx: ^1.1.0
  flutter_mobx: ^1.0.1
  flutter_local_notifications: ^1.3.0
  date_utils: ^0.1.0
  scrollable_positioned_list: ^0.1.2
  flutter_slidable: ^0.5.4
  modal_bottom_sheet: ^0.1.4

  # prerelease
  flutter_native_dialog: 
    git:
      url: git@github.com:sadne/flutter_native_dialog.git
      ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  json_serializable: ^3.3.0
  mobx_codegen: ^1.0.3
flutter:
  assets:
   - assets/images/
  fonts:
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf
